### ISSUE TITLE
How to create cStor Volumes with Single replica?

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#486]
Found this on the OpenEBS Community Channel (YoavZ). 

> I’m working on small sized K8s cluster (using cstor).
> Is it possible to configure openebs not to go pending before there are 3 replicas.
> I want it to go live even with 1 replica.

The following solution worked:
- Create a SPC with maxPools set to 1
- Create a StorageClass specifying the ReplicaCount as 1

(The samples can be found at: https://github.com/openebs/openebs/tree/master/k8s/sample-pv-yamls )

It will be great to have this clearly called out in the documentation.

**Comment by ranjithwingrider** [comment]
You can give the `maxPools` count as `1` in StoragePoolClaim YAML and `replicaCount` as `1` in StorageClass YAML.
In the following sample SPC and SC YAML, cStor pool is created using auto method. Using auto method, it will take single attached disk. After applying this YAML, one cStor pool named `cstor-disk` will create only in one Node with StorageClass named `openebs-cstor-disk`. 
Only requirement is that one node has atleast one disk attached but unmounted. See [here](https://docs.openebs.io/docs/next/faq.html#what-must-be-the-disk-mount-status-on-node-for-provisioning-openebs-volume) to understand more about disk mount status
```
---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk
spec:
  name: cstor-disk
  type: disk
  maxPools: 1
  poolSpec:
    poolType: striped
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi
```
