### ISSUE TITLE
How to configure and use a specific file system for OpenEBS Jiva volume?

### ISSUE THREAD

**Issue by ranjithwingrider** [openebs/openebs-docs#495]
How to configure and use a specific file system like ext3, ext4,XFS etc for provisioning OpenEBS Jiva volume?

**Comment by ranjithwingrider** [comment]
OpenEBS supports ext3,ext4 and XFS file systems. By default, it comes with ext4 file system for the mounted volumes. Some applications require using the XFS as file system. The policy to specify XFS as the file system, you must add `openebs.io/fstype: "xfs"`under section annotations:

----

Following is a sample storage class for application which need to be run on XFS. Similar way I can change the FSType to ext3. Below is the sample StorageClass YAML I have used for using ext3 filesystem.
```
kind: StorageClass
metadata:
   name: openebs-ext3
   annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ControllerImage
        value: openebs/jiva:0.8.0
      - name: ReplicaImage
        value: openebs/jiva:0.8.0
      - name: VolumeMonitorImage
        value: openebs/m-exporter:0.8.0
      - name: ReplicaCount
        value: "1"
      - name: StoragePool
        value: default
      - name: FSType
        value: "ext3"
      #- name: TargetResourceLimits
      #  value: |-
      #      memory: 1Gi
      #      cpu: 100m
      #- name: AuxResourceLimits
      #  value: |-
      #      memory: 0.5Gi
      #      cpu: 50m
      #- name: ReplicaResourceLimits
      #  value: |-
      #      memory: 2Gi
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
```
