### ISSUE TITLE
How do I reuse an existing PV - after re-creating Kubernetes StatefulSet and its PVC

### ISSUE THREAD

**Issue by kmova** [openebs/openebs-docs#569]
## Description

Due to some application issue I had to delete the StatefulSet and re-install a new StatefulSet. In the process I also deleted the PVCs used by the StatefulSet. However, before deleting the PVCs I patched the PVs to be retained. 

However when I recreated the STS, a PVC object got created with same name as previous time, but it was bound to a new PV. 

## Expected Behavior

I wanted the PVC (with same name) to be bound to the older PV which had the data. 

## Current Behavior

Everytime a PVC is created, openebs provisioner tries to check if a PV object exists with name pvc-<uuid-of-pvc>. If not it creates a new PVC.  This causes the PVC to not bind to older PV. 

## Possible Solution

Delete the STS and the associated PVCs. 

* Create a new PVC with the same name as the one that STS creates. Specify the old PV name under the volumeName in the in PVC spec:
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
    labels:
      environment: test
      openebs.io/replica-anti-affinity: vehicle-db
      role: mongo
    name: mongo-persistent-storage-mongo-0
    namespace: default
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5G
    storageClassName: mongo-pv-az
    volumeName: pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5G
  ```
* The PVC looks like:
  ```
  NAME                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
  mongo-persistent-storage-mongo-0   Lost      pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   0                        mongo-pv-az    4s
  ```   
* Get the newly created PVC UID using `kubectl get pvc mongo-persistent-storage-mongo-0  -o yaml`

* Update the uid under the claimRef in the PV. `kubectl edit pv pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7`

* The PVC will get attached to the PV. 
  ```
  NAME                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
  mongo-persistent-storage-mongo-0   Bound     pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            mongo-pv-az    5m
  ```

* Create the STS. The pod will come back online by re-using the existing PVC (that was manually created above). 

## Steps to Reproduce

I have a STS running successfully, with one replica. I see the following objects running: 
- Application Pod ( from the STS)
  ```
  NAME                                                             READY     STATUS    RESTARTS   AGE
  mongo-0                                                          2/2       Running   0          1m
  ```
- PV and PVC for the above application
  ```
  NAME                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
  mongo-persistent-storage-mongo-0   Bound     pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            mongo-pv-az    2m
  ```

- I patched the PV to retain using the steps explained [here](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume):

  ```
  NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                      STORAGECLASS   REASON    AGE
  pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            Retain           Bound     default/mongo-persistent-storage-mongo-0   mongo-pv-az              9m
  ```

- I now deleted the STS and the associated PVC. As expected the PV was not deleted. 

- When I recreated the STS. A new PVC was created. However a new PV also got created. 
  ```
  NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                      STORAGECLASS   REASON    AGE
  pvc-c12cf109-52ea-11e9-b1ef-42010a800fe7   5G         RWO            Delete           Bound      default/mongo-persistent-storage-mongo-0   mongo-pv-az              19s
  pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            Retain           Released   default/mongo-persistent-storage-mongo-0   mongo-pv-az              14m
  ```

**Comment by ranjithwingrider** [comment]
There are some cases where it may need to delete the StatefulSet and re-install a new StatefulSet. In the process you may have to delete the PVCs used by the StatefulSet and retain PV policy by ensuring the Retain as the "Reclaim Policy". In this case, following are the procedures for re-using an existing PV in your recreated StatefulSet application.
1. Get the PV name by following command and use it in Step 2.
```
kubectl get pv
```
Following is an example output
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                      STORAGECLASS   REASON    AGE
pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            Delete           Bound     default/mongo-persistent-storage-mongo-0   mongo-pv-az              9m
```
2. Patch corresponding PV's reclaim policy from "Delete" to "Retain". So that PV will retain even its PVC is deleted.This can be done by using the steps mentioned [here](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume).

Example Output:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                      STORAGECLASS   REASON    AGE
pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            Retain           Bound     default/mongo-persistent-storage-mongo-0   mongo-pv-az              9m
```
3. Get the PVC name by following command and note down the PVC name. You have to use this same PVC name while creating new PVC.
```
kubectl get pvc
```
Example Output:
```
NAME                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mongo-persistent-storage-mongo-0   Lost      pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   0                        mongo-pv-az    4s
```
4. Delete StatefulSet application and associated PVCs.
5. Create a new PVC YAML named newPVC.yaml with same configuration. Specify old PV name belongs to volumeName under the PVC spec.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
  labels:
    environment: test
    openebs.io/replica-anti-affinity: vehicle-db
    role: mongo
  name: mongo-persistent-storage-mongo-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: mongo-pv-az
  volumeName: pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5G
```
6. Apply the modified PVC YAML using the following command
```
kubectl apply -f newPVC.yaml
```
Example Output:
```
NAME                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mongo-persistent-storage-mongo-0   Lost      pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   0                        mongo-pv-az    4s
```
7. Get the newly created PVC UID using `kubectl get pvc mongo-persistent-storage-mongo-0 -o yaml`.

8. Update the uid under the claimRef in the PV using the following command. The PVC will get attached to the PV after editing the pv with correct uid.
```
kubectl edit pv pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7
```
9. Get the updated PVC status using the following command.
```
kubectl get pvc
```
Example Output:
```
NAME                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mongo-persistent-storage-mongo-0   Bound     pvc-cc6767b4-52e8-11e9-b1ef-42010a800fe7   5G         RWO            mongo-pv-az    5m
```
10. Apply the same StatefulSet application YAML. The pod will come back online by re-using the existing PVC. The application pod status can be get by following command.
```
kubectl get pods -n <namespace>
```
