### ISSUE TITLE
spc created, but csp missing

### ISSUE THREAD

**Issue by fogs** [openebs/openebs-docs#599]
I have created a spc according to https://docs.openebs.io/docs/next/ugcstor.html#creating-cStor-storage-pools. Upon apply, the spc gets created, the csp is not showing up.

Took me a while to find the relevant log entry:
```
E0623 11:11:55.241055       6 handler.go:213] Unable to get pending pool count for spc cstor-disk-pool:failed to get pending pool count for spc cstor-disk-pool: error in max pool value in spc cstor-disk-pool: validation of spc object is failed as no max pool field present in spc cstor-disk-pool
```

**Comment by ranjithwingrider** [comment]
Thanks @fogs  for the find.
Basically, with the latest 1.0 version maxPools is not being used. The error is due to typo in the below section
```
 poolSpec:
    poolType: striped
  blockdevices:
    blockDeviceList:
```
In above snippet, use `blockDevice` instead of `blockdevice`.
so correct SPC yaml is below.
```
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
   #  - blockdevice-936911c5c9b0218ed59e64009cc83c8f
   #  - blockdevice-77f834edba45b03318d9de5b79af0734
   #  - blockdevice-1c10eb1bb14c94f02a00373f2fa09b93
```
I am changing the same in the documentation. It will reflect in some time.
